import assert from 'node:assert/strict'
import { once } from 'node:events'
import { createServer, get as httpGet, request as httpRequest } from 'node:http'
import type { Server } from 'node:http'
import { mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { pathToFileURL } from 'node:url'

import express from 'express'

import { createWorkerSessionHost, forwardToSessionHost } from './session-host.ts'
import type { SessionHost } from './session-host.ts'

async function listen(server: Server): Promise<number> {
  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve))
  const address = server.address()
  if (!address || typeof address !== 'object') throw new Error('no address')
  return address.port
}

function fetchLocal(port: number, pathname: string, init: RequestInit = {}): Promise<globalThis.Response> {
  return fetch(`http://127.0.0.1:${port}${pathname}`, init)
}

async function waitFor(predicate: () => boolean, timeoutMs = 15_000): Promise<void> {
  const deadline = Date.now() + timeoutMs
  while (!predicate()) {
    if (Date.now() > deadline) throw new Error('condition not reached in time')
    await new Promise((resolve) => setTimeout(resolve, 50))
  }
}

test('forward streams chunked responses progressively and preserves host', async () => {
  const seenHeaders: Record<string, string | string[] | undefined>[] = []
  let releaseSecondChunk = () => {}
  const upstream = createServer((req, res) => {
    seenHeaders.push({ ...req.headers })
    res.writeHead(200, { 'content-type': 'text/event-stream', connection: 'keep-alive' })
    res.write('data: first\n\n')
    releaseSecondChunk = () => res.end('data: second\n\n')
  })
  const upstreamPort = await listen(upstream)

  const app = express()
  app.use('/baton/v1', (req, res) => forwardToSessionHost({ port: upstreamPort, token: 'secret' }, req, res))
  const front = createServer(app)
  const frontPort = await listen(front)

  try {
    const chunks: string[] = []
    const firstChunk = new Promise<void>((resolve, reject) => {
      const request = httpGet({
        host: '127.0.0.1',
        port: frontPort,
        path: '/baton/v1/stream',
        // `proxy-authorization` is hop-by-hop and never auto-generated by
        // Node's client, so its absence upstream proves client hop-by-hop
        // headers are stripped (Node regenerates `connection` per hop).
        headers: { host: `127.0.0.1:${frontPort}`, 'proxy-authorization': 'Basic x-should-not-forward' },
      }, (response) => {
        assert.equal(response.statusCode, 200)
        response.setEncoding('utf8')
        response.on('data', (chunk: string) => {
          chunks.push(chunk)
          resolve()
        })
        response.on('end', () => resolve())
      })
      request.once('error', reject)
    })
    await firstChunk
    // The first SSE chunk arrived while the upstream response is still open.
    assert.ok(chunks.join('').includes('data: first'))
    releaseSecondChunk()
    await waitFor(() => chunks.join('').includes('data: second'))

    const forwarded = seenHeaders[0]
    assert.equal(forwarded?.host, `127.0.0.1:${frontPort}`)
    assert.equal(forwarded?.['x-baton-session-host'], 'secret')
    assert.equal(forwarded?.['proxy-authorization'], undefined)
  } finally {
    front.close()
    upstream.close()
    front.closeAllConnections()
    upstream.closeAllConnections()
  }
})

test('forward returns 502 when the session host is unreachable', async () => {
  const app = express()
  // Nothing listens on this port: bind+close to reserve an unused one.
  const probe = createServer()
  const deadPort = await listen(probe)
  await new Promise((resolve) => probe.close(resolve))
  app.use('/baton/v1', (req, res) => forwardToSessionHost({ port: deadPort, token: 't' }, req, res))
  const front = createServer(app)
  const frontPort = await listen(front)
  try {
    const response = await fetchLocal(frontPort, '/baton/v1/sessions')
    assert.equal(response.status, 502)
    const body = await response.json() as { error?: { type?: string } }
    assert.equal(body.error?.type, 'baton_session_host_unreachable')
  } finally {
    front.close()
    front.closeAllConnections()
  }
})

test('client disconnect aborts the upstream request', async () => {
  let upstreamAborted = false
  const upstream = createServer((_req, res) => {
    res.writeHead(200, { 'content-type': 'text/event-stream' })
    res.write('data: open\n\n')
    res.once('close', () => { upstreamAborted = true })
  })
  const upstreamPort = await listen(upstream)
  const app = express()
  app.use('/baton/v1', (req, res) => forwardToSessionHost({ port: upstreamPort, token: 't' }, req, res))
  const front = createServer(app)
  const frontPort = await listen(front)
  try {
    const request = httpRequest({ host: '127.0.0.1', port: frontPort, path: '/baton/v1/stream' })
    request.end()
    await once(request, 'response')
    request.destroy()
    await waitFor(() => upstreamAborted)
  } finally {
    front.close()
    upstream.close()
    front.closeAllConnections()
    upstream.closeAllConnections()
  }
})

test('worker session host serves the real runtime and refuses tokenless direct access', async () => {
  const dataDir = await mkdtemp(path.join(tmpdir(), 'baton-session-host-'))
  let host: SessionHost | null = null
  const front = createServer()
  try {
    host = createWorkerSessionHost({ dataDir })
    const app = express()
    app.use('/baton/v1', host.middleware)
    front.on('request', app)
    const frontPort = await listen(front)

    await waitFor(() => host!.snapshot().state === 'ready')
    const permissions = await fetchLocal(frontPort, '/baton/v1/permissions')
    assert.equal(permissions.status, 200)
    const sessions = await fetchLocal(frontPort, '/baton/v1/sessions')
    assert.equal(sessions.status, 200)

    // CSRF probe proves the Host header survives the hop: the runtime compares
    // the Origin header against the host the client addressed.
    const csrf = await fetchLocal(frontPort, '/baton/v1/native-import/csrf', {
      headers: {
        'sec-fetch-site': 'same-origin',
        origin: `http://127.0.0.1:${frontPort}`,
      },
    })
    assert.equal(csrf.status, 200)

    await host.close()
    const afterClose = await fetchLocal(frontPort, '/baton/v1/sessions')
    assert.equal(afterClose.status, 503)
    host = null
  } finally {
    front.close()
    front.closeAllConnections()
    if (host) await host.close()
    await rm(dataDir, { recursive: true, force: true })
  }
})

test('worker session host restarts after an unexpected worker death', async () => {
  const dataDir = await mkdtemp(path.join(tmpdir(), 'baton-session-host-crash-'))
  const fixture = path.join(dataDir, 'crashy-worker.mjs')
  // Protocol-compatible fixture: serves one OK, dies on demand.
  await writeFile(fixture, `
import { createServer } from 'node:http'
import { parentPort } from 'node:worker_threads'
const server = createServer((req, res) => {
  if (req.url.endsWith('/crash')) {
    res.writeHead(200).end('crashing')
    setTimeout(() => process.exit(1), 10)
    return
  }
  res.writeHead(200, { 'content-type': 'application/json' }).end('{"ok":true}')
})
server.listen(0, '127.0.0.1', () => {
  parentPort.postMessage({ type: 'listening', port: server.address().port, token: 'fixture' })
  parentPort.postMessage({ type: 'started', recovered: 0 })
})
parentPort.on('message', (m) => { if (m?.type === 'shutdown') process.exit(0) })
`, 'utf8')

  const host = createWorkerSessionHost({ dataDir, workerUrl: pathToFileURL(fixture) })
  const app = express()
  app.use('/baton/v1', host.middleware)
  const front = createServer(app)
  const frontPort = await listen(front)
  try {
    await waitFor(() => host.snapshot().state === 'ready')
    assert.equal((await fetchLocal(frontPort, '/baton/v1/anything')).status, 200)

    await fetchLocal(frontPort, '/baton/v1/crash')
    await waitFor(() => host.snapshot().state !== 'ready')
    assert.equal((await fetchLocal(frontPort, '/baton/v1/anything')).status, 503)

    // The supervisor relaunches the worker on its backoff ladder.
    await waitFor(() => host.snapshot().state === 'ready')
    assert.equal((await fetchLocal(frontPort, '/baton/v1/anything')).status, 200)
    assert.ok(host.snapshot().restarts >= 1)
  } finally {
    front.close()
    front.closeAllConnections()
    await host.close()
    await rm(dataDir, { recursive: true, force: true })
  }
})
